import Head from "next/head";
import { useStore, AppState } from "~/store";
import Input from "~/ui/Input";

export default function Home() {
  // store
  const appState = useStore((state) => state.appState);
  const setSeconds = useStore((state) => state.setSeconds);
  const addNumber = useStore((state) => state.addNumber);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {appState === AppState.PENDING && (
          <Input label="seconds" name="seconds" setValue={setSeconds} />
        )}
        {(appState === AppState.READY || appState === AppState.RUNNING) && (
          <Input label="number" name="number" setValue={addNumber} />
        )}
      </main>
    </>
  );
}
